config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
		confirmations: 'users/confirmations',
		passwords: 'users/passwords',
		registrations: 'users/registrations',
		sessions: 'users/sessions',
		omiauth_callbacks: 'users/omniauth_callbacks'
	}

	resources :visualize do
	end

	resources :brands do
	end

	# brands trades stock_accoujntsはユーザが登録する場合のみ(現状)
	namespace :admin do
    root 'top#index'
    get :stock_price_to_chart, path: "brands/stock_price_to_chart", to: "brands#stock_price_to_chart", format: :json
    get :production_trend_chart, path: "brands/production_trend_chart", to: "brands#production_trend_chart", format: :json
    get :index_to_chart, path: "top/index_to_chart", to: "top#index_to_chart", format: :json
		resources :brands, param: :code, except: [:destroy]
		resource :brands, only: [:destroy]
		resources :fields
		resources :markets
    resources :tags
		resources :stcok_accounts, only: [:index, :show]
		resources :stock_companies, except: [:destroy]
		resource :stock_companies, only: [:destroy]
		resources :trading_histories, except: [:destroy]
		resources :users
		resources :stock_analyses, only: [:index] do
      collection do
        post "analysis"
        post "import_index"
      end
    end
	end
end

app/models/stock_company.rb
# == Schema Information
#
# Table name: stock_companies
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  info       :text(65535)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class StockCompany < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/admin/stock_companies_controller.rb
class Admin::StockCompaniesController < ApplicationController
  before_action :store_stock_company, only: [:create]
  before_action :fetch_stock_company, only: [:show, :edit, :update]

  def new
    @stock_company = StockCompany.new
  end

  def create
    @stock_company = StockCompany.new(store_stock_company)
    if @stock_company.save
      # TODO: error detail
      flash[:notice] = ["create new stock company"]
      return render "sample/index"
    else
      flash[:alert] = @stock_company.errors.full_messages
      return redirect_to action: :new
    end
  end

  def index
    @stock_companies = StockCompany.page(params[:page]).per(10).order("created_at DESC")
  end

  def edit
  end

  def update
    if @stock_company.update(store_stock_company)
      # TODO: error detail
      flash[:notice] = ["update stock company"]
      redirect_to action: :index
    else
      flash[:alert] = @stock_company.errors.full_messages
      render "edit"
    end
  end

  def destroy
    checked_items = params[:checked_item].keys
    StockCompany.delete(checked_items)
    # TODO: message
    flash[:notice] = ["delete stock company"]
    redirect_to action: :index
  end

  private

  def store_stock_company
    params.require(:stock_company).permit(:name, :info)
  end

  def fetch_stock_company
    @stock_company = StockCompany.find_by(id: params[:id])
  end
end

app/helpers/admin/stock_companies_helper.rb
module Admin::StockCompaniesHelper
end

app/views/admin/stock_companies/_form.html.slim
.col-md-12
  .box.box-primary
    .box-header.with-border
      h3.box-title
        i.fa.fa-edit
        |  Please input follows
    form role="form"
      .box-body
        .form-group
          = f.label :name
          = f.text_field :name, class: "form-control", placeholder: "Company Name"
        .form-group
          = f.label :info
          = f.text_area :info, class: "form-control", placeholder: "Refference", rows: 10
      .box-footer
        - if edit_flg == true
          = f.submit t('views.admin.update'), class: "btn btn-primary"
        - else
          = f.submit t('views.admin.submit'), class: "btn btn-primary"

app/views/admin/stock_companies/edit.html.slim
- breadcrumb :edit_stock_company, @stock_company

section.content
  = form_for(@stock_company, url: admin_stock_company_path, action: 'update') do |f|
    = render partial: 'form', locals: { f: f, edit_flg: true }

app/views/admin/stock_companies/index.html.slim
- breadcrumb :stock_companies

section.content
  .row
    .col-xs-12
      .box
        .box-header
          = form_tag "/admin/stock_companies", method: "delete" do
            = submit_tag t('views.admin.destroy'), class: "btn btn-danger"
            = ' '
            = link_to t('views.admin.new'), new_admin_stock_company_path, class: "btn btn-default", type: :button
            .box-body
              .dataTables_wrapper.form-inline.dt-bootstrap
                .row
                  .col-sm-12
                    table.table.table-bordered.table-hover.dataTable
                      th
                        = check_box_tag 'check_all_box'
                      th
                        = t('admin.stock_companies.name')
                      th
                        = t('admin.stock_companies.info')
                      th
                      tbody
                        - @stock_companies.each do |stock_company|
                          tr
                            td
                              = check_box_tag "checked_item[#{stock_company.id}]", '', false, class: 'checked_item'
                            td.col-sm-4
                              h5
                                = stock_company.name
                            td.col-sm-7
                              h5
                                = stock_company.info
                            td.col-sm-1
                              = link_to t('views.admin.edit'), edit_admin_stock_company_path(stock_company), class: "btn btn-default"
                = page_entries_info @stock_companies
              = paginate @stock_companies

app/views/admin/stock_companies/new.html.slim
- breadcrumb :new_stock_company, @stock_company

section.content
  = form_for(@stock_company, url: admin_stock_companies_path) do |f|
    = render partial: 'form', locals: { f: f, edit_flg: false }