config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
		confirmations: 'users/confirmations',
		passwords: 'users/passwords',
		registrations: 'users/registrations',
		sessions: 'users/sessions',
		omiauth_callbacks: 'users/omniauth_callbacks'
	}

	resources :visualize do
	end

	resources :brands do
	end

	# brands trades stock_accoujntsはユーザが登録する場合のみ(現状)
	namespace :admin do
    root 'top#index'
    get :stock_price_to_chart, path: "brands/stock_price_to_chart", to: "brands#stock_price_to_chart", format: :json
    get :production_trend_chart, path: "brands/production_trend_chart", to: "brands#production_trend_chart", format: :json
    get :index_to_chart, path: "top/index_to_chart", to: "top#index_to_chart", format: :json
		resources :brands, param: :code, except: [:destroy]
		resource :brands, only: [:destroy]
		resources :fields
		resources :markets
    resources :tags
		resources :stcok_accounts, only: [:index, :show]
		resources :stock_companies, except: [:destroy]
		resource :stock_companies, only: [:destroy]
		resources :trading_histories, except: [:destroy]
		resources :users
		resources :stock_analyses, only: [:index] do
      collection do
        post "analysis"
        post "import_index"
      end
    end
	end
end

app/models/trading_history.rb
# == Schema Information
#
# Table name: trading_histories
#
#  id             :integer          not null, primary key
#  purchase_date  :date             not null
#  code           :integer          not null
#  purchase_price :integer          not null
#  stock_number   :integer          not null
#  disposal_date  :date
#  disposal_price :integer
#  profit         :integer
#  tag            :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class TradingHistory < ActiveRecord::Base
  has_many :tags, through: :trade_tags
  has_many :trade_tags
  belongs_to :brand, foreign_key: "code", primary_key: "code"

  accepts_nested_attributes_for :trade_tags, allow_destroy: true

  # attr_accessor :name
  attr_accessor :tag_ids

  validates :purchase_date, presence: true
  validates :code, presence: true, numericality: :only_integer
  validates :purchase_price, presence: true, numericality: :only_integer
  validates :stock_number, presence: true, numericality: :only_integer

  scope :current_month_profit, -> {
    where("DATE_FORMAT(disposal_date, '%Y%m') = DATE_FORMAT(NOW(), '%Y%m')")
      .sum(:profit).to_s(:delimited)
  }
  scope :current_week_profit, -> {
    where(disposal_date: [5.days.ago..Date.current])
      .sum(:profit).to_s(:delimited)
  }

  def save_tags
    old_tags = tags.pluck(:tag_id).map(&:to_s)
    new_tags = tag_ids if tag_ids.present?
    current_tags = new_tags.present? ? new_tags - old_tags : []
    old_tags -= new_tags if new_tags
    current_tags.each do |current_tag|
      TradeTag.create(trading_history_id: id, tag_id: current_tag)
    end
    old_tags.each do |old_tag|
      TradeTag.where(trading_history_id: id, tag_id: old_tag).destroy_all
    end
  end
end

app/controllers/admin/trading_histories_controller.rb
class Admin::TradingHistoriesController < ApplicationController
  before_action :store_trading_history, only: [:create]
  before_action :fetch_trading_history, only: [:show, :edit, :update]

  def new
    @trading_history = TradingHistory.new
    @trading_history.purchase_date = Date.current
  end

  def create
    @trading_history = TradingHistory.new(store_trading_history)
    if @trading_history.save
      @trading_history.save_tags
      # TODO: error detail
      flash[:notice] = ["create new trading_history"]
      redirect_to action: "index"
    else
      flash[:alert] = @trading_history.errors.full_messages
      return redirect_to action: :new
    end
  end

  def index
    @q = TradingHistory.ransack(params[:q])
    @trading_histories = @q.result.page(params[:page]).per(10).order("created_at DESC")
    @total_profit = TradingHistory.sum(:profit).to_s(:delimited)
    @current_month_profit = TradingHistory.current_month_profit
    @current_week_profit = TradingHistory.current_week_profit
  end

  def edit
  end

  def update
    if @trading_history.update(store_trading_history)
      @trading_history.save_tags
      # TODO: error detail
      flash[:notice] = ["update trading_history"]
      redirect_to action: "index"
    else
      flash[:alert] = @trading_history.errors.full_messages
      render "edit"
    end
  end

  private

  def store_trading_history
    trading_history = params.require(:trading_history).permit(
      :purchase_date,
      :code,
      :purchase_price,
      :stock_number,
      :disposal_date,
      :disposal_price
    )
    trading_history[:tag_ids] = params[:trading_history][:tag_ids].slice(1..-1)
    disposal_price = trading_history[:disposal_price]
    if disposal_price.present?
      profit = (disposal_price.to_i - trading_history[:purchase_price].to_i) * trading_history[:stock_number].to_i
      trading_history[:profit] = profit
    end
    trading_history
  end

  def fetch_trading_history
    @trading_history = TradingHistory.find_by(id: params[:id])
  end
end

app/helpers/admin/trading_histories_helper.rb
module Admin::TradingHistoriesHelper
  def select_tags
    Tag.all.pluck(:name, :id)
  end
end

app/views/admin/trading_histories/_form.html.slim
.col-md-12
  .box.box-primary
    .box-header.with-border
      h3.box-title
        i.fa.fa-edit
        |  Please input follows
    form role="form"
      .box-body
        .form-group
          div.row
            .col-sm-2
              = f.label :purchase_date
            .col-sm-10
              = f.date_field :purchase_date, class: "form-control"
        .form-group
          div.row
            .col-sm-2
              = f.label :code
            .col-sm-10
              = f.text_field :code, class: "form-control"
        .form-group
          div.row
            .col-sm-2
              = f.label :purchase_price
            .col-sm-10
              = f.text_field :purchase_price, class: "form-control"
        .form-group
          div.row
            .col-sm-2
              = f.label :stock_number
            .col-sm-10
              = f.text_field :stock_number, class: "form-control"
        .form-group
          div.row
            .col-sm-2
              = f.label :disposal_date
            .col-sm-10
              = f.date_field :disposal_date, class: "form-control"
        .form-group
          div.row
            .col-sm-2
              = f.label TradingHistory.human_attribute_name(:tags)
            .col-sm-10
              = f.select :tag_ids, select_tags, {}, class: "form-control select2", multiple: true
        .form-group
          div.row
            .col-sm-2
              = f.label :disposal_price
            .col-sm-10
              = f.text_field :disposal_price, class: "form-control"
      .box-footer.text-center
        - if edit_flg == true
          = f.submit t('views.admin.update'), class: "btn btn-primary"
        - else
          = f.submit t('views.admin.submit'), class: "btn btn-primary"

app/views/admin/trading_histories/edit.html.slim
- breadcrumb :edit_trading_history, @trading_history

section.content
  = form_for(@trading_history, url: admin_trading_history_path, action: 'update') do |f|
    = render partial: 'form', locals: { f: f, edit_flg: true }

app/views/admin/trading_histories/index.html.slim
- breadcrumb :trading_histories

section.content
  .row
    .col-xs-12
      .box
        br
        .row
          .col-sm-4
            .small-box.bg-aqua
              .inner
                h3
                  = @total_profit
                p
                  = t('admin.trading_histories.total_profit')
              .icon
                i.fa.fa-shopping-cart
          .col-sm-4
            .small-box.bg-green
              .inner
                h3
                  = @current_month_profit
                p
                  = t('admin.trading_histories.current_month_profit')
              .icon
                i.fa.fa-line-chart
          .col-sm-4
            .small-box.bg-yellow
              .inner
                h3
                  = @current_week_profit
                p
                  = t('admin.trading_histories.current_week_profit')
              .icon
                i.fa.fa-retweet
        .box-header
          <!-- TODO  -->
          = link_to t('views.admin.new'), new_admin_trading_history_path, class: "btn btn-default", type: :button
        .box-body
          .dataTables_wrapper.form-inline.dt-bootstrap
            .row
              .col-sm-12
                table.table.table-bordered.table-hover.dataTable
                  th.text-center
                    = sort_link @q, :purchase_date
                  th.text-center
                    = t('admin.trading_histories.code')
                  th.text-center
                    = t('admin.trading_histories.name')
                  th.text-center
                    = t('admin.trading_histories.purchase_price')
                  th.text-center
                    = t('admin.trading_histories.stock_number')
                  th.text-center
                    = sort_link @q, :disposal_date
                  th.text-center
                    = t('admin.trading_histories.disposal_price')
                  th.text-center
                    = sort_link @q, :profit
                  th.text-center
                    = t('admin.trading_histories.tag')
                  th
                  tbody
                    - @trading_histories.each do |trading_history|
                      tr
                        td.col-sm-1.text-center
                          h5
                            = trading_history.purchase_date
                        td.col-sm-1.text-center
                          h5
                            = link_to trading_history.code, admin_brand_path(trading_history.code)
                        td.col-sm-1.text-center
                          h5
                            = trading_history.brand.try(:name)
                        td.col-sm-1.text-center
                          h5
                            = trading_history.purchase_price
                        td.col-sm-1.text-center
                          h5
                            = trading_history.stock_number
                        td.col-sm-1.text-center
                          h5
                            = trading_history.disposal_date
                        td.col-sm-1.text-center
                          h5
                            = trading_history.disposal_price
                        td.col-sm-1.text-center style="color: #{trading_history.profit.to_i > 0 ? 'green' : 'red'}"
                          h5
                            = trading_history.profit
                        td.col-sm-1.text-center
                          -  trading_history.tags.each do |tag|
                            .label style="background-color: #{ tag.color }"
                              = tag.name
                        td.col-sm-1.text-center
                          = link_to t('views.admin.edit'), edit_admin_trading_history_path(trading_history), class: "btn btn-default"
                = page_entries_info @trading_histories
            = paginate @trading_histories

app/views/admin/trading_histories/new.html.slim
- breadcrumb :new_trading_history, @trading_history

section.content
  = form_for(@trading_history, url: admin_trading_histories_path) do |f|
    = render partial: 'form', locals: { f: f, edit_flg: false }