config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
		confirmations: 'users/confirmations',
		passwords: 'users/passwords',
		registrations: 'users/registrations',
		sessions: 'users/sessions',
		omiauth_callbacks: 'users/omniauth_callbacks'
	}

	resources :visualize do
	end

	resources :brands do
	end

	# brands trades stock_accoujntsはユーザが登録する場合のみ(現状)
	namespace :admin do
    root 'top#index'
    get :stock_price_to_chart, path: "brands/stock_price_to_chart", to: "brands#stock_price_to_chart", format: :json
    get :production_trend_chart, path: "brands/production_trend_chart", to: "brands#production_trend_chart", format: :json
    get :index_to_chart, path: "top/index_to_chart", to: "top#index_to_chart", format: :json
		resources :brands, param: :code, except: [:destroy]
		resource :brands, only: [:destroy]
		resources :fields
		resources :markets
    resources :tags
		resources :stcok_accounts, only: [:index, :show]
		resources :stock_companies, except: [:destroy]
		resource :stock_companies, only: [:destroy]
		resources :trading_histories, except: [:destroy]
		resources :users
		resources :stock_analyses, only: [:index] do
      collection do
        post "analysis"
        post "import_index"
      end
    end
	end
end

app/models/market.rb
# == Schema Information
#
# Table name: markets
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  info       :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Market < ActiveRecord::Base
end

app/controllers/admin/markets_controller.rb
class Admin::MarketsController < ApplicationController
  before_action :store_market, only: [:create]
  before_action :fetch_market, only: [:show, :edit, :update]

  def new
    @market = Market.new
  end

  def create
    @market = Market.new(store_market)
    if @market.save
      # TODO: error detail
      flash[:notice] = ["create new market"]
      return render "sample/index"
    else
      flash[:alert] = @market.errors.full_messages
      return redirect_to action: :new
    end
  end

  def index
    @markets = Market.page(params[:page]).per(10).order("created_at DESC")
  end

  def edit
  end

  def update
    if @market.update(store_market)
      # TODO: error detail
      flash[:notice] = ["update market"]
      redirect_to action: :index
    else
      flash[:alert] = @market.errors.full_messages
      render "edit"
    end
  end

  private

  def store_market
    params.require(:market).permit(:name, :info)
  end

  def fetch_market
    @market = Market.find_by(id: params[:id])
  end
end

app/helpers/admin/markets_helper.rb
module Admin::MarketsHelper
end

app/views/admin/markets/_form.html.slim
.col-md-12
  .box.box-primary
    .box-header.with-border
      h3.box-title
        i.fa.fa-edit
        |  Please input follows
    form role="form"
      .box-body
        .form-group
          = f.label :name
          = f.text_field :name, class: "form-control", placeholder: "Market Name"
        .form-group
          = f.label :info
          = f.text_area :info, class: "form-control", placeholder: "Refference", rows: 10
      .box-footer
        - if edit_flg == true
          = f.submit t('views.admin.update'), class: "btn btn-primary"
        - else
          = f.submit t('views.admin.submit'), class: "btn btn-primary"

app/views/admin/markets/edit.html.slim
- breadcrumb :edit_market, @market

section.content
  = form_for(@market, url: admin_market_path, action: 'update') do |f|
    = render partial: 'form', locals: { f: f, edit_flg: true }

app/views/admin/markets/index.html.slim
- breadcrumb :markets

section.content
  .row
    .col-xs-12
      .box
        .box-header
          <!-- TODO  -->
          = link_to t('views.admin.destroy'), new_admin_market_path, class: "btn btn-danger", type: :button
          = ' '
          = link_to t('views.admin.new'), new_admin_market_path, class: "btn btn-default", type: :button
        .box-body
          .dataTables_wrapper.form-inline.dt-bootstrap
            .row
              .col-sm-12
                table.table.table-bordered.table-hover.dataTable
                  th
                    = check_box_tag ''
                  th
                    = t('admin.markets.name')
                  th
                    = t('admin.markets.info')
                  th
                  tbody
                    - @markets.each do |market|
                      tr
                        td
                          = check_box_tag 'checked_item', market.id
                        td.col-sm-4
                          h5
                            = market.name
                        td.col-sm-7
                          h5
                            = market.info
                        td.col-sm-1
                          = link_to t('views.admin.edit'), edit_admin_market_path(market), class: "btn btn-default"
                = page_entries_info @markets
            = paginate @markets

app/views/admin/markets/new.html.slim
- breadcrumb :new_market, @market

section.content
  = form_for(@market, url: admin_markets_path) do |f|
    = render partial: 'form', locals: { f: f, edit_flg: false }