config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
		confirmations: 'users/confirmations',
		passwords: 'users/passwords',
		registrations: 'users/registrations',
		sessions: 'users/sessions',
		omiauth_callbacks: 'users/omniauth_callbacks'
	}

	resources :visualize do
	end

	resources :brands do
	end

	# brands trades stock_accoujntsはユーザが登録する場合のみ(現状)
	namespace :admin do
    root 'top#index'
    get :stock_price_to_chart, path: "brands/stock_price_to_chart", to: "brands#stock_price_to_chart", format: :json
    get :production_trend_chart, path: "brands/production_trend_chart", to: "brands#production_trend_chart", format: :json
    get :index_to_chart, path: "top/index_to_chart", to: "top#index_to_chart", format: :json
		resources :brands, param: :code, except: [:destroy]
		resource :brands, only: [:destroy]
		resources :fields
		resources :markets
    resources :tags
		resources :stcok_accounts, only: [:index, :show]
		resources :stock_companies, except: [:destroy]
		resource :stock_companies, only: [:destroy]
		resources :trading_histories, except: [:destroy]
		resources :users
		resources :stock_analyses, only: [:index] do
      collection do
        post "analysis"
        post "import_index"
      end
    end
	end
end

app/views/layouts/application.html.slim
html
  head
    title Adminlte
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags

  body.skin-red data-controller="#{controller.controller_path}" data-action="#{controller.action_name}"
    div.wrapper
      header.main-header
        = link_to t("views.admin.top"), admin_root_path, { class: "logo" }
        nav.navbar.navbar-static-top role="navigation"
          a.sidebar-toggle data-toggle="offcanvas" role= "button"
          ul.nav.navbar-nav
            li
              = link_to "Navigation1", {}
            li
              = link_to "Navigation2", {}
          .navbar-custom-menu
            ul.nav.navbar-nav
              li

      side.main-sidebar
        section.sidebar
          ul.sidebar-menu
            .user-panel
              .pull-left.image
              .pull-left.info
            li.header 機能一覧
            li.treeview
              = link_to "#", class: "i fa fa-check-square"
                = "　" + t("views.admin.user")
                span.pull-right-container
                  i.fa.fa-angle-left.pull-right
              ul.treeview-menu
                li
                  = link_to "#", class: "i fa fa-check-square-o"
                    |　test
                li
                  = link_to "#", class: "i fa fa-check-square-o"
                    |　test
                li
                  = link_to "#", class: "i fa fa-check-square-o"
                    |　test
            li
              = link_to "#", class: "i fa fa-check-square"
                = "　" + t("views.admin.stock_account")
            li
              = link_to admin_stock_companies_path, class: "i fa fa-check-square"
                = "　" + t("views.admin.stock_company")
            li
              = link_to "#", class: "i fa fa-check-square"
                = "　" + t("views.admin.field")
            li
              = link_to admin_markets_path, class: "i fa fa-check-square"
                = "　" + t("views.admin.market")
            li
              = link_to admin_brands_path, class: "i fa fa-check-square"
                = "　" + t("views.admin.brands")
            li
              = link_to admin_tags_path, class: "i fa fa-check-square"
                = "　" + t("views.admin.tags")
            li
              = link_to admin_stock_analyses_path, class: "i fa fa-check-square"
                = "　" + t("views.admin.stock_analysis")
            li
              = link_to admin_trading_histories_path, class: "i fa fa-check-square"
                = "　" + t("views.admin.trading_history")

      div.content-wrapper
        section.content-header
          h3
            == breadcrumbs separator: " / "
        - flash.each do |key, vals|
          - key = key == "notice" ? "success" : "danger"
          = content_tag :div, class: "alert alert-#{key}"
            - vals.each do |val|
              - concat content_tag :i, val, class: "icon fa fa-check"
            - concat content_tag :button, "×", class: "close", "data-dismiss" => "alert"
        = yield
        = javascript_include_tag "application", "data-turbolinks-track" => true

      footer.main-footer
        div.pull-right.hidden-xs Version1.0
        strong Copyright &copy; 2016
        |  All rights reserved.

app/views/layouts/visualize.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>graph_visualization</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
	<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>